*** S/R CHANGE JJHHMM EN MINUTES
      FUNCTION JHMENM( JJHHMM )
  
      IMPLICIT NONE 
  
      INTEGER    JHMENM, JJHHMM
  
*ARGUMENTS
* SORTIE  JHMENM -  MINUTES
* ENTRE   JJHHMM -  JOURS-HEURES-MINUTES
*
*     AUTEUR - Y. R. BOURASSA FEV 91
*
*     LANGUAGE FTN77
  
      INTEGER  J, H, M
  
*     EXTRACTIOPN DES JOURS, HEURES & MINUTES
      J = JJHHMM/10000
      H = (JJHHMM-(J*10000))/100
      M = JJHHMM-(J*10000)-(H*100)
 
      JHMENM = ((J*24)+H)*60+M


      RETURN
      END 
