SHELL=/bin/sh

.SUFFIXES   :.cdk90 .f90 .f .c .o
COMPILE.F90 = r.compile -src
BUILD.F90   = r.build -obj
DEBUG        = -debug
DEBUG        = 
CF90        = f90
LIB_OBJECTS = burp_constants.o \
              f2kcli.o \
              errormessages.o \
              librmn_declaration.o \
              object_initialization.o \
              conversion_to_string.o

BURP_OBJECTS= burp_block_class.o \
              burp_rpt_class.o \
              burp_file_class.o
SUPP_OBJECTS= burp_btyp_runn_flgs.o
#SUPP_OBJECTS= 

FLAGS       =  -Wl,-L/users/dor/afsd/hmd/userlibs/IRIX64 -Wl,\
               -L/usr/local/env/armnlib/lib/IRIX64 -n32 \
	       -I. -I/usr/local/env/armnlib/include -O1 



.cdk90.o               :
	$(COMPILE.F90) $< $(DEBUG) 
        
.f90.o                 :
	$(COMPILE.F90) $< $(DEBUG) 

read_burp              : read_burp.o 
	$(BUILD.F90) $(LIB_OBJECTS) $(BURP_OBJECTS) $(SUPP_OBJECTS)\
        $@.o $(DEBUG) -librmn -o $@

read_burp.o            :$(SUPP_OBJECTS) burp_module

write_burp             : write_burp.o 
	$(BUILD.F90) $(LIB_OBJECTS) $(BURP_OBJECTS) $(SUPP_OBJECTS)\
        $@.o $(DEBUG) -librmn -o $@

write_burp.o           : $(SUPP_OBJECTS) burp_module

burp_module            : $(LIB_OBJECTS) $(BURP_OBJECTS)

burp_block_class.o     : $(LIB_OBJECTS)
burp_rpt_class.o       : burp_block_class.o
burp_file_class.o      : burp_rpt_class.o
#burp_btyp_runn_flgs.o  : burp_module 
burp_btyp_runn_flgs.o  : burp_file_class.o






tidy     :
	rm -f *.o

clean    : tidy
	rm -f *.export *.so *.sl *.a *.mod \
	read1 read2 write1 write2 read_burp \
	write_burp

inc_mode : burp_module $(SUPP_OBJECTS)
	@echo "OS type detected: " `/bin/uname`
	@case `/bin/uname` in \
	"IRIX64" )  \
	cp  *.mod include/IRIX64/ ;;\
	"Linux" )  \
	cp  *.mod include/Linux/ ;;\
	*) echo "This system is not supported" ;; \
	esac

library  : inc_mode 
	@echo "OS type detected: " `/bin/uname`
	@case `/bin/uname` in \
	"IRIX64" )  \
	cp $(LIB_OBJECTS) $(BURP_OBJECTS) $(SUPP_OBJECTS) lib/IRIX64/ ;;\
	"Linux" )  \
	cp $(LIB_OBJECTS) $(BURP_OBJECTS) $(SUPP_OBJECTS) lib/Linux/ ;;\
	*) echo "This system is not supported" ;; \
	esac


#	$(CF90) $@.f90 -Iinclude $(FLAGS) -o $@  lib/*.o -lrmn 


clean_lib:
	rm -f include/Linux/*
	rm -f lib/Linux/*
	rm -f include/IRIX64/*
	rm -f lib/IRIX64/*


