MODULE OBJECT_INITIALIZATION
     IMPLICIT NONE
     PRIVATE
     CHARACTER, PARAMETER:: INITIAL='*'
     INTEGER             :: ID_LAST=0

     TYPE T_INIT; PRIVATE
             INTEGER   :: ID
             CHARACTER :: DATA
     END TYPE

     TYPE(T_INIT), PARAMETER, PUBLIC:: INIT_0 = T_INIT(0,INITIAL)
     PUBLIC :: T_INIT, IS_INIT, INITIALIZE, TEST_INIT, GET_ID,GET_DATA

     CONTAINS

     LOGICAL FUNCTION IS_INIT(INIT)
             TYPE(T_INIT), INTENT(IN) :: INIT
             IS_INIT = (INIT%DATA==INITIAL).AND.INIT%ID>0.AND.INIT%ID<=ID_LAST
     END FUNCTION

     SUBROUTINE INITIALIZE (INIT)
             TYPE(T_INIT), INTENT(OUT) :: INIT
             ID_LAST = ID_LAST +1
             INIT = T_INIT(ID_LAST,INITIAL)
     END SUBROUTINE

     SUBROUTINE TEST_INIT (INIT)
             TYPE(T_INIT), INTENT(INOUT) :: INIT
             IF(.NOT.IS_INIT(INIT)) CALL INITIALIZE(INIT)
     END SUBROUTINE

     INTEGER FUNCTION GET_ID(INIT)
             TYPE(T_INIT), INTENT(IN) :: INIT
             GET_ID = INIT%ID
     END FUNCTION

     CHARACTER FUNCTION GET_DATA(INIT)
             TYPE(T_INIT), INTENT(IN) :: INIT
             GET_DATA= INIT%DATA
     END FUNCTION


END MODULE OBJECT_INITIALIZATION
