all:
	d.compile -o libburp_idl.so -src libburp_idl.c -optc =-Wl,-rpath=/ssm/net/rpn/libs/15.2/ubuntu-10.04-amd64-64/lib/Linux_x86-64/intel13sp1u2,-rpath=/ssm/net/hpcs/201402/01/intel13sp1u2/multi/lib/intel64 -conly -librmn rmnshared_015.2
